### ISSUE TITLE
MudaeCraft not detecting discord?

### ISSUE THREAD

**Issue by aydinyas** [MedicV2/MudaeCraft#2]
![Screenshot 2024-07-18 091026](https://github.com/user-attachments/assets/aa9e34a2-1139-486a-bc72-ca5d61c7812e)

Just using this in my own service for fun and it was working properly but now it seems to have stopped? The screenshot I sent was just to show that I do have installed correctly and have the right settings on but it did not claim the character that the kakeravalue was set to. The only reasonable explanation that I could think of is that it no longer has access to view discord? I say this as when I had used this before it would have a red circle on the tab with discord like it was recording. (I am not a code expertise just my conclusion based on my observations, I do apologize if I have misunderstood and may have unintentionally done something wrong.)

**Comment by MedicV2** [comment]
Ahh, I see! I will fix it asap. You can add me on discord @Medc , I'll update you on things when it's done.

**Comment by aydinyas** [comment]
> Ahh, I see! I will fix it asap. You can add me on discord @medc , I'll update you on things when it's done.

No worries, just thought I would let you know. Ii sent a friend request if you would like to accept it @.aydinm.
